/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Complaints */
        get: operations["list_complaints_api_complaints_get"];
        put?: never;
        /** Create Complaint */
        post: operations["create_complaint_api_complaints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints/{complaint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Complaint */
        get: operations["get_complaint_api_complaints__complaint_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints/{complaint_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Status */
        patch: operations["change_status_api_complaints__complaint_id__status_patch"];
        trace?: never;
    };
    "/api/meta/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Providers */
        get: operations["get_providers_api_meta_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Category
         * @enum {string}
         */
        Category: "water" | "electricity" | "sanitation" | "roads" | "streetlights" | "other";
        /** ComplaintCreate */
        ComplaintCreate: {
            /** Location */
            location: string;
            /** Reporter Contact */
            reporter_contact?: string | null;
            /** Text */
            text: string;
        };
        /** ComplaintOut */
        ComplaintOut: {
            /** Ai Summary */
            ai_summary?: string | null;
            /** Allowed Transitions */
            allowed_transitions: components["schemas"]["Status"][];
            category: components["schemas"]["Category"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location */
            location: string;
            priority: components["schemas"]["Priority"];
            /** Reporter Contact */
            reporter_contact: string | null;
            status: components["schemas"]["Status"];
            /** Text */
            text: string;
            /** Triage Confidence */
            triage_confidence: number | null;
            /** Triage Latency Ms */
            triage_latency_ms: number;
            /** Triaged By */
            triaged_by: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ComplaintPage */
        ComplaintPage: {
            /** Items */
            items: components["schemas"]["ComplaintOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
            /** Total */
            total: number;
        };
        /**
         * ErrorBody
         * @description The one envelope every 4xx/5xx response uses (plan D6).
         */
        ErrorBody: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Allowed */
            allowed?: components["schemas"]["Status"][] | null;
            /** Code */
            code: string;
            /** Fields */
            fields?: components["schemas"]["FieldError"][] | null;
            from_status?: components["schemas"]["Status"] | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Retry After S */
            retry_after_s?: number | null;
            to_status?: components["schemas"]["Status"] | null;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
            /** Type */
            type: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "high" | "normal" | "low";
        /** ProvidersOut */
        ProvidersOut: {
            /** Active Provider */
            active_provider: string;
            /** Cache Hit Rate */
            cache_hit_rate: number | null;
            /** Fallback Provider */
            fallback_provider: string;
            /** Model */
            model: string | null;
            /** Recent */
            recent: components["schemas"]["TriageOutcomeOut"][];
        };
        /** StatsOut */
        StatsOut: {
            /** By Category */
            by_category: {
                [key: string]: number;
            };
            /** By Priority */
            by_priority: {
                [key: string]: number;
            };
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Total */
            total: number;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "open" | "in_progress" | "resolved" | "rejected";
        /** StatusUpdate */
        StatusUpdate: {
            status: components["schemas"]["Status"];
        };
        /** TriageOutcomeOut */
        TriageOutcomeOut: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Cache Hit */
            cache_hit: boolean;
            /**
             * Complaint Id
             * Format: uuid
             */
            complaint_id: string;
            /** Error Class */
            error_class: string | null;
            /** Fallback */
            fallback: boolean;
            /** Latency Ms */
            latency_ms: number;
            /** Provider */
            provider: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_complaints_api_complaints_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["Category"] | null;
                priority?: components["schemas"]["Priority"] | null;
                status?: components["schemas"]["Status"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintPage"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_complaint_api_complaints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplaintCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintOut"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Rate limited; see Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_complaint_api_complaints__complaint_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                complaint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintOut"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Complaint not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    change_status_api_complaints__complaint_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                complaint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintOut"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Complaint not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid status transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_providers_api_meta_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersOut"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
