import datetime as dt
from typing import Any, ClassVar

from sqlalchemy import DateTime, MetaData
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.sql.type_api import TypeEngine

# Deterministic constraint/index names (e.g. ck_complaints_text_length) so
# autogenerated Alembic diffs stay clean and downgrades are reliable.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    # Every Mapped[datetime] is timestamptz, never a naive timestamp. ClassVar
    # because DeclarativeBase reads this at class-creation time, not per instance.
    type_annotation_map: ClassVar[dict[type, TypeEngine[Any]]] = {dt.datetime: DateTime(timezone=True)}
